### PR TITLE
Hide footer when there is 5 or less results

### PR DESCRIPTION
**Pull request by marcindo**
This is for better presentation, when there is not enough results to make more than one page anyway

### CODE REVIEW

**Comment by adi130987** [comment]
Great ideea, but I would use `totalPages` instead of `totalResults`... if there is just one page, do not show the footer

**Comment by marcindo** [comment]
Using `totalPages` has one caveat - it depends on current page size. So let's say I have 7 results, but size 10 - which means only one page, but I still should have an option to switch to 5 per page and get two pages in result. And with bigger page sizes this would be even more limiting

**Comment by adi130987** [comment]
you're right... I'll create a new version in a few minutes.

**Comment by adi130987** [comment]
@marcindo your ideea is implemented in `v1.1.0`. Thanks.

**Pull request closed without merging**
